[tool.poetry]
name = "restful-service-demo"
version = "0.1.0"
description = ""
authors = ["Eoin Dowling <avieor1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
SQLAlchemy = "^2.0.31"
ngrok = "^1.3.0"
marshmallow = "^3.21.3"
flask = "^3.0.3"
flask-ngrok = "^0.0.25"
flask-sqlalchemy = "^3.1.1"
flask-marshmallow = "^1.2.1"
marshmallow-sqlalchemy = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
